version: '3'

services:
  app2:
    build: .
    ports:
      - "9000:9000"
    networks:
      - api_bridge_network
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - '.:/var/www/html'

  mysql:
    image: mysql:5.7
    ports:
      - "3308:3306"
    networks:
      - api_bridge_network
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - db_data_app2:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    networks:
      - api_bridge_network
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'

volumes:
  db_data_app2:

networks:
  api_bridge_network:
    driver: bridge